clc; clear all;
close all;
%% Load data
Calc1=load('Calc_TwoLevel.mat');
Calc2=load('Calc_TwoLevel2.mat');
w = Calc1.Details.objects(1).w;
w0 = Calc1.Details.objects(1).w0;
del = w - w0;
k_max2 = Calc1.Details.objects(1).k_max2;
V_range = Calc1.Details.variables.V_range;
nV = length(V_range);
%% Plot Calc1
% TODO: energy plots are broken
plotObj = Plot.TwoLevel(Calc1.Details.objects(2));
zoom_rect(1) = Plot.rect(sqrt(w^2-del^2) + [-2E-5 2E-5],[-5E-6 5E-6]);
zoom_rect(2) = Plot.rect(sqrt(4*w^2-del^2) + [-2E-5 2E-5],[-5E-6 5E-6] - w/2);
[fg(1),ax(1)] = plotObj.Energy(V_range,...
    Ebar=permute(reshape([Calc1.Res_Unpert_AE.Ebar],1,nV,2),[2 3 1]),...
    eps=permute(reshape([Calc1.Res_Unpert_AE.eps],1,nV,2),[2 3 1]),...
    P=permute(reshape([Calc1.Res_Unpert_AE.P],k_max2,nV,2),[2 3 1]),...
    File='PlotB25.png');
plotObj.calcObj=Calc1.Details.objects(1);
[fg(2),ax(2)] = plotObj.Energy(V_range,...
    Ebar=permute(reshape([Calc1.Res_Pert_AE.Ebar],1,nV,2),[2 3 1]),...
    eps=permute(reshape([Calc1.Res_Pert_AE.eps],1,nV,2),[2 3 1]),...
    P=permute(reshape([Calc1.Res_Pert_AE.P],k_max2,nV,2),[2 3 1]),...
    zooms=zoom_rect(1),...
    File='PlotB25-1.png');
[fg(3),ax(3)] = plotObj.Energy(V_range,...
    eps=permute(reshape([Calc1.Res_Pert_QE.eps],1,nV,2),[2 3 1]),...
    P=permute(reshape([Calc1.Res_Pert_QE.P],k_max2,nV,2),[2 3 1]),...
    zooms=zoom_rect,...
    File='PlotB25-2.png');
%% Plot Calc2
plotObj.calcObj=Calc2.Details.objects(2);
[fg(4),ax(4)] = plotObj.Variational_th(Calc2.Res_Unpert_AE,...
    File='PlotB26.png');
[fg(5),ax(5)] = plotObj.Variational_th(Calc2.Res_Unpert_QE,...
    File='PlotB26-1.png');
[fg(6),ax(6)] = plotObj.Variational_Overlap(Calc2.Res_Unpert_AE,1,...
    File='PlotB26-2.png',normalized=false);
[fg(7),ax(7)] = plotObj.Variational_Overlap(Calc2.Res_Unpert_QE,1,...
    File='PlotB26-3.png',normalized=false);
[fg(8),ax(8)] = plotObj.Variational_Overlap(Calc2.Res_Unpert_AE,1,...
    File='PlotB26-4.png',normalized=true);
[fg(9),ax(9)] = plotObj.Variational_Overlap(Calc2.Res_Unpert_QE,1,...
    File='PlotB26-5.png',normalized=true);
plotObj.calcObj=Calc2.Details.objects(1);
[fg(10),ax(10)] = plotObj.Variational_th(Calc2.Res_Pert_AE,...
    File='PlotB27.png');
[fg(11),ax(11)] = plotObj.Variational_th(Calc2.Res_Pert_QE,...
    File='PlotB27-1.png');
[fg(12),ax(12)] = plotObj.Variational_Overlap(Calc2.Res_Pert_AE,1,...
    File='PlotB27-2.png',normalized=false);
[fg(13),ax(13)] = plotObj.Variational_Overlap(Calc2.Res_Pert_QE,1,...
    File='PlotB27-3.png',normalized=false);
[fg(14),ax(14)] = plotObj.Variational_Overlap(Calc2.Res_Pert_AE,1,...
    File='PlotB27-4.png',normalized=true);
[fg(15),ax(15)] = plotObj.Variational_Overlap(Calc2.Res_Pert_QE,1,...
    File='PlotB27-5.png',normalized=true);
plotObj.calcObj=Calc2.Details.objects(3);
[fg(10),ax(10)] = plotObj.Variational_th(Calc2.Res_Pert2_AE,...
    File='PlotB28.png');
[fg(12),ax(12)] = plotObj.Variational_Overlap(Calc2.Res_Pert2_AE,1,...
    File='PlotB28-1.png',normalized=false);
[fg(14),ax(14)] = plotObj.Variational_Overlap(Calc2.Res_Pert2_AE,1,...
    File='PlotB28-2.png',normalized=true);