clc; clear all;
w0=1;w=1.5;v=1E-6;
xi=1E-3; tol=1E-12;
Unpert = QuanFloq.Models.TwoLevel(w0=w0,w=w,k_max=100,v=0,xi=tol,...
    RWA=false,rand_v=true);
Pert = QuanFloq.Models.TwoLevel(w0=w0,w=w,k_max=100,v=v,xi=xi,...
    RWA=false,rand_v=true);
V = 1.7035769013796129;
Unpert.V = V;
Pert.V = V;
th_range=linspace(-pi/2,pi/2,21);
nth = length(th_range);
%% Save calculation metadata
Details = QuanFloq.Details(script='Calc_TwoLevelNonRWA2.m',...
    model='Two-level system noRWA [cos(w*t)]',...
    calculation='Variational Floquet eigenstate convergence',...
    objects=[Pert,Unpert],...
    variables=struct(V=V,th_range=th_range));
%% Calculate exact eigenstates
[Res_Ex.Psi,Res_Ex.eps,Res_Ex.Ebar] = Unpert.eigs;
%% Calculate eigenstates
Psi0=[cos(th_range);sin(th_range)];
fprintf('(Unpert) Doing AE variational principle:\n');tic;
Res_Unpert_AE = Unpert.variational('AE',Psi0=Psi0,...
    TrackPsi=true,filter_nconv=false,tol=tol);
fprintf('(Unpert) Done AE method: %f (s)\n',toc);
fprintf('(Unpert) Doing QE variance variational principle:\n');tic;
Res_Unpert_QE = Unpert.variational('varQE',Psi0=Psi0,...
    TrackPsi=true,filter_nconv=false,tol=tol);
fprintf('(Unpert) Done QE method: %f (s)\n',toc);
fprintf('(Pert) Doing AE variational principle:\n');tic;
Res_Pert_AE = Pert.variational('AE',Psi0=Psi0,...
    TrackPsi=true,filter_nconv=false,tol=tol);
fprintf('(Pert) Done AE method: %f (s)\n',toc);
fprintf('(Pert) Doing QE variance variational principle:\n');tic;
Res_Pert_QE = Pert.variational('varQE',Psi0=Psi0,...
    TrackPsi=true,filter_nconv=false,tol=tol);
fprintf('(Pert) Done QE method: %f (s)\n',toc);
%% PostProcess
Processer = Process.TwoLevel(Unpert);
Res_Unpert_AE = Processer.Variational(Res_Unpert_AE,...
    th=true,Norm=true,Ex_Psi=Res_Ex.Psi);
Res_Unpert_QE = Processer.Variational(Res_Unpert_QE,...
    th=true,Norm=true,Ex_Psi=Res_Ex.Psi);
Processer.calcObj = Pert;
Res_Pert_AE = Processer.Variational(Res_Pert_AE,...
    th=true,Norm=true,Ex_Psi=Res_Ex.Psi);
Res_Pert_QE = Processer.Variational(Res_Pert_QE,...
    th=true,Norm=true,Ex_Psi=Res_Ex.Psi);
%% Save results
save('Calc_TwoLevelNonRWA2.mat',...
    'Res_Unpert_QE','Res_Unpert_AE',...
    'Res_Pert_QE','Res_Pert_AE',...
    'Details',...
    '-v7.3');

