clc; clear all;
close all;
%% Load data
Calc1=load('Calc_TwoLevelNonRWA.mat');
Calc2=load('Calc_TwoLevelNonRWA2.mat');
Calc3=load('Calc_TwoLevelNonRWA3.mat');
w = Calc1.Details.objects(1).w;
k_max2 = Calc1.Details.objects(1).k_max2;
V_range = Calc1.Details.variables.V_range;
nV = length(V_range);
%% Plot Calc1
plotObj = Plot.TwoLevel(Calc1.Details.objects(2));
zoom_rect(1) = Plot.rect(1.7035769013796129 + [-2E-5 2E-5],[-5E-6 5E-6]);
zoom_rect(2) = Plot.rect(4.0843758839750000 + [-2E-5 2E-5],[-5E-6 5E-6] - w);
[fg(1),ax(1)] = plotObj.Energy(V_range,...
    Ebar=permute(reshape([Calc1.Res_Unpert_AE.Ebar],1,nV,2),[2 3 1]),...
    eps=permute(reshape([Calc1.Res_Unpert_AE.eps],1,nV,2),[2 3 1]),...
    P=permute(reshape([Calc1.Res_Unpert_AE.P],k_max2,nV,2),[2 3 1]),...
    File='PlotB22.png');
plotObj.calcObj=Calc1.Details.objects(1);
[fg(2),ax(2)] = plotObj.Energy(V_range,...
    Ebar=permute(reshape([Calc1.Res_Pert_AE.Ebar],1,nV,2),[2 3 1]),...
    eps=permute(reshape([Calc1.Res_Pert_AE.eps],1,nV,2),[2 3 1]),...
    P=permute(reshape([Calc1.Res_Pert_AE.P],k_max2,nV,2),[2 3 1]),...
    zooms=zoom_rect(1),...
    File='PlotB22-1.png');
[fg(3),ax(3)] = plotObj.Energy(V_range,...
    eps=permute(reshape([Calc1.Res_Pert_QE.eps],1,nV,2),[2 3 1]),...
    P=permute(reshape([Calc1.Res_Pert_QE.P],k_max2,nV,2),[2 3 1]),...
    zooms=zoom_rect,...
    File='PlotB22-2.png');
%% Plot Calc2
plotObj.calcObj=Calc2.Details.objects(2);
[fg(4),ax(4)] = plotObj.Variational_th(Calc2.Res_Unpert_AE,...
    File='PlotB23.png');
[fg(5),ax(5)] = plotObj.Variational_th(Calc2.Res_Unpert_QE,...
    File='PlotB23-1.png');
[fg(6),ax(6)] = plotObj.Variational_Overlap(Calc2.Res_Unpert_AE,1,...
    File='PlotB23-2.png',normalized=false);
[fg(7),ax(7)] = plotObj.Variational_Overlap(Calc2.Res_Unpert_QE,1,...
    File='PlotB23-3.png',normalized=false);
[fg(8),ax(8)] = plotObj.Variational_Overlap(Calc2.Res_Unpert_AE,1,...
    File='PlotB23-4.png',normalized=true);
[fg(9),ax(9)] = plotObj.Variational_Overlap(Calc2.Res_Unpert_QE,1,...
    File='PlotB23-5.png',normalized=true);
plotObj.calcObj=Calc2.Details.objects(1);
[fg(10),ax(10)] = plotObj.Variational_th(Calc2.Res_Pert_AE,...
    File='PlotB24.png');
[fg(11),ax(11)] = plotObj.Variational_th(Calc2.Res_Pert_QE,...
    File='PlotB24-1.png');
[fg(12),ax(12)] = plotObj.Variational_Overlap(Calc2.Res_Pert_AE,1,...
    File='PlotB24-2.png',normalized=false);
[fg(13),ax(13)] = plotObj.Variational_Overlap(Calc2.Res_Pert_QE,1,...
    File='PlotB24-3.png',normalized=false);
[fg(14),ax(14)] = plotObj.Variational_Overlap(Calc2.Res_Pert_AE,1,...
    File='PlotB24-4.png',normalized=true);
[fg(15),ax(15)] = plotObj.Variational_Overlap(Calc2.Res_Pert_QE,1,...
    File='PlotB24-5.png',normalized=true);
%% Plot Calc3
plotObj.calcObj=Calc3.Details.objects(1);
overlap = reshape([Calc3.Res_10B.OverlapMeasure],3,[]);
[fg(16),ax(16)] = plotObj.SteadyState(Calc3.Details.variables.V_range,...
    rhoz=[Calc3.Res_10B.rhoz],...
    overlapM=[Calc3.Res_0K.OverlapMeasure2],...
    File='PlotB34.png');